export const ISSUES_SISYPHUS_PERMISSION = {
  edit: "deny" as const,
  bash: {
    // ===== READ-ONLY COMMANDS (from Planner-Sisyphus) =====
    "cut*": "allow" as const,
    "diff*": "allow" as const,
    "du*": "allow" as const,
    "file *": "allow" as const,
    "find * -delete*": "ask" as const,
    "find * -exec*": "ask" as const,
    "find * -fprint*": "ask" as const,
    "find * -fls*": "ask" as const,
    "find * -fprintf*": "ask" as const,
    "find * -ok*": "ask" as const,
    "find *": "allow" as const,
    "grep*": "allow" as const,
    "head*": "allow" as const,
    "less*": "allow" as const,
    "ls*": "allow" as const,
    "more*": "allow" as const,
    "pwd*": "allow" as const,
    "rg*": "allow" as const,
    "sort --output=*": "ask" as const,
    "sort -o *": "ask" as const,
    "sort*": "allow" as const,
    "stat*": "allow" as const,
    "tail*": "allow" as const,
    "tree -o *": "ask" as const,
    "tree*": "allow" as const,
    "uniq*": "allow" as const,
    "wc*": "allow" as const,
    "whereis*": "allow" as const,
    "which*": "allow" as const,
    "cat*": "allow" as const,
    "echo*": "allow" as const,
    
    // ===== GIT READ-ONLY =====
    "git diff*": "allow" as const,
    "git log*": "allow" as const,
    "git show*": "allow" as const,
    "git status*": "allow" as const,
    "git branch": "allow" as const,
    "git branch -v": "allow" as const,
    "git branch -a": "allow" as const,
    "git remote*": "allow" as const,
    "git rev-parse*": "allow" as const,
    "git ls-files*": "allow" as const,
    "git blame*": "allow" as const,

    // ===== GITHUB CLI - FULL ACCESS =====
    "gh *": "allow" as const,

    // ===== DENY DESTRUCTIVE GIT OPERATIONS =====
    "git commit*": "deny" as const,
    "git push*": "deny" as const,
    "git pull*": "deny" as const,
    "git checkout*": "deny" as const,
    "git merge*": "deny" as const,
    "git rebase*": "deny" as const,
    "git reset*": "deny" as const,
    "git stash*": "deny" as const,
    "git add*": "deny" as const,
    "git rm*": "deny" as const,
    "git mv*": "deny" as const,

    // ===== DENY BUILD/DEPLOY =====
    "dotnet*": "deny" as const,
    "npm *": "deny" as const,
    "yarn *": "deny" as const,
    "pnpm *": "deny" as const,
    "bun run*": "deny" as const,
    "cargo *": "deny" as const,
    "pip *": "deny" as const,
    "python *": "deny" as const,

    // ===== DEFAULT =====
    "*": "ask" as const,
  },
  webfetch: "allow" as const,
};
